services:
  backoffice:
    image: ghcr.io/${GHCR_NAMESPACE:-proyectohornero}/hornero-backoffice:latest
    build: .
    container_name: hornero-backoffice
    ports:
      - "3001:80"
    networks:
      - hornero-network

networks:
  hornero-network:
    driver: bridge
