services:
  backoffice:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: hornero-backoffice
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.backoffice
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - hornero-network

networks:
  hornero-network:
    external: true
